# docker network create -d overlay --subnet=10.1.0.0/16 --gateway=10.1.0.1 myhero_default
# docker stack deploy --compose-file docker-stack.yml myhero
version: '3.0'

networks:
  default:

services:
  data:
    hostname: myhero_data
    image: hpreston/myhero_data
    networks:
      - "default"
    ports:
    - 10101:5000/tcp
    volumes:
    - /docker/myhero/myhero_data:/app:rw
    environment:
      - myhero_data_key=e009ae3c3b80e73c0c768561b077e82e
    deploy:
      replicas: 3
      labels:
        feature.description: "Data"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

  mosca:
    hostname: myhero_mosca
    image: matteocollina/mosca
    networks:
      - "default"
    ports:
    - 10701:80/tcp
    volumes:
    - /docker/myhero/myhero_mosca:/app:rw
    environment:
      - myhero_data_key=e009ae3c3b80e73c0c768561b077e82e
      - myhero_data_server=http://myhero_data:5000
      - myhero_mqtt_host=http://myhero_mosca:5000
      - myhero_mqtt_port=1883
    depends_on:
    - data
    deploy:
      replicas: 2
      labels:
        feature.description: "Mosca"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

  ernst:
    hostname: myhero_ernst
    image: hpreston/myhero_ernst
    networks:
      - "default"
    ports:
    - 10801:5000/tcp
    volumes:
    - /docker/myhero/myhero_ernst:/app:rw
    environment:
      - myhero_data_key=e009ae3c3b80e73c0c768561b077e82e
      - myhero_data_server=http://myhero_data:5000
      - myhero_mqtt_host=myhero_mosca
      - myhero_mqtt_server=myhero_mosca
      - myhero_mqtt_port=1883
    depends_on:
    - mosca
    - data
    deploy:
      replicas: 2
      labels:
        feature.description: "Ernst"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

  app:
    hostname: myhero_app
    image: hpreston/myhero_app
    networks:
      - "default"
    ports:
    - 10201:5000/tcp
    volumes:
    - /docker/myhero/myhero_app:/app:rw
    environment:
      - myhero_data_key=e009ae3c3b80e73c0c768561b077e82e
      - myhero_data_server=http://myhero_data:5000
      - myhero_app_key=e009ae3c3b80e73c0c768561b077e82f
      #- myhero_app_mode=direct
      - myhero_app_mode=queue
      - myhero_mqtt_host=myhero_mosca
      - myhero_mqtt_server=myhero_mosca
      - myhero_mqtt_port=1883
    depends_on:
    - ernst
    deploy:
      replicas: 3
      labels:
        feature.description: "App"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

  web:
    hostname: myhero_web
    image: hpreston/myhero_web
    networks:
      - "default"
    ports:
    - 10301:5000/tcp
    volumes:
    - /docker/myhero/myhero_web:/app:rw
    environment:
      - myhero_app_key=e009ae3c3b80e73c0c768561b077e82f
      - myhero_app_server=http://myhero_app:5000
    depends_on:
    - app
    deploy:
      replicas: 1
      labels:
        feature.description: "Web"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

  ui:
    hostname: myhero_ui
    image: hpreston/myhero_ui
    networks:
      - "default"
    ports:
    - 10401:80/tcp
    volumes:
    - /docker/myhero/myhero_ui:/app:rw
    environment:
      - myhero_app_server=http://164.177.189.155:10201
      - myhero_app_key=e009ae3c3b80e73c0c768561b077e82f
      - myhero_spark_server=http://164.177.189.155:10501
      - myhero_tropo_server=http://164.177.189.155:10601
    depends_on:
    - app
    deploy:
      replicas: 1
      labels:
        feature.description: "UI"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

  spark:
    hostname: myhero_spark
    image: hpreston/myhero_spark
    networks:
      - "default"
    ports:
    - 10501:5000/tcp
    volumes:
    - /docker/myhero/myhero_spark:/app:rw
    environment:
      - myhero_app_key=e009ae3c3b80e73c0c768561b077e82f
      - myhero_app_server=http://myhero_app:5000
      #- spark_token=Y2lzY29zcGFyazovL3VzL0FQUExJQ0FUSU9OL2Q2NjEwZWUxLTI0Y2YtNGM1MS1iNzAwLTRlOGE0ZDlhZDBhNQ
      #- myhero_spark_bot_email=MyHeroBot@sparkbot.io
      - spark_token=NmVhMzliY2ItZTI3ZS00MzA0LTgxNTEtZjU0MDllMTczNDE1MzZkMzAxZmMtNWI3
      - myhero_spark_bot_email=guillain.sanchez@dimensiondata.com
      - myhero_spark_bot_url=http://164.177.189.155:10501
      - myhero_spark_bot_secret=e009ae3c3b80e73c0c768561b077e82g
      - myhero_spark_roomid=Y2lzY29zcGFyazovL3VzL1JPT00vMzg3NzcwYjAtMGI0OS0xMWU4LWI5MGUtM2IzY2I5ZmM5MGMy
    depends_on:
    - app
    deploy:
      replicas: 1
      labels:
        feature.description: "Spark"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

  tropo:
    hostname: myhero_tropo
    image: hpreston/myhero_tropo
    networks:
      - "default"
    ports:
    - 10601:5000/tcp
    volumes:
    - /docker/myhero/myhero_tropo:/app:rw
    environment:
      - myhero_app_key=e009ae3c3b80e73c0c768561b077e82f
      - myhero_app_server=http://myhero_app:5000
      - myhero_tropo_secret=e009ae3c3b80e73c0c768561b077e82h
      - myhero_tropo_user=guillain
      - myhero_tropo_pass=Sucemab1te!
      - myhero_tropo_prefix=1678
      - myhero_tropo_url=http://164.177.189.155:10601
    depends_on:
    - app
    deploy:
      replicas: 1
      labels:
        feature.description: "Tropo"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

